apiVersion: builtin
kind: PatchStrategicMergeTransformer
metadata:
  name: smp-hgc
patches: |-
  ---
  apiVersion: airshipit.org/v1alpha1
  kind: VariableCatalogue
  metadata:
    name: host-generation-catalogue
  $patch: delete
