# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include_tasks: autodetect.yaml

- include_tasks: domain.yaml
  vars:
    console_log_enabled: "{{ libvirt_domain.console_log_enabled | default(false) }}"
    console_log_path: >-
      {{ libvirt_domain.console_log_path |
         default(libvirt_vm_default_console_log_dir + '/' +  libvirt_domain.name + '-console.log', true) }}
    machine_default: "{{ none if libvirt_vm_engine == 'kvm' else 'pc-1.0' }}"
    machine: "{{ libvirt_domain.machine | default(machine_default, true) }}"
    cpu_mode: "{{ libvirt_domain.cpu_mode | default(libvirt_cpu_mode_default) }}"
    volumes: "{{ libvirt_domain.volumes | default([], true) }}"
    interfaces: "{{ libvirt_domain.interfaces | default([], true) }}"
    start: "{{ libvirt_domain.start | default(true) }}"
    autostart: "{{ libvirt_domain.autostart | default(true) }}"
    enable_vnc: "{{ libvirt_domain.enable_vnc | default(false) }}"
