apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capd

patchesJson6902:
  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "target-cluster-control-plane"
    path: machine_count.json
