# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: config.kubernetes.io/v1alpha1
kind: ResourceList
items: []
functionConfig:
  apiVersion: airshipit.org/v1alpha1
  kind: IsoConfiguration
  metadata:
    annotations:
      config.kubernetes.io/function: |-
        container:
          image: krm-function-cloud-init:latest
    name: cloud-init
  builder:
    userDataSelector:
      kind: Secret
      labelSelector: airshipit.org/ephemeral-user-data
    userDataKey: userData
    networkConfigSelector:
      kind: BareMetalHost
      labelSelector: airshipit.org/ephemeral-node
    networkConfigKey: networkData
