apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: target-cluster-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackMachineTemplate
    name: target-cluster-control-plane
  kubeadmConfigSpec:
    files:
    - path: /etc/kubernetes/cloud.conf
      content: W0dsb2JhbF0KYXV0aC11cmw9aHR0cDovLzEwLjAuMC40L2lkZW50aXR5CnVzZXJuYW1lPSJkZW1vIgpwYXNzd29yZD0icGFzcyIKdGVuYW50LW5hbWU9ImRlbW8iCmRvbWFpbi1pZD0iZGVmYXVsdCIKcmVnaW9uPSJSZWdpb25PbmUiCg==
      encoding: base64
      owner: root
      permissions: "0600"
    - path: /etc/certs/cacert
      content: Cg==
      encoding: base64
      owner: root
      permissions: "0600"
