apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capo

patchesJson6902:

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: OpenStackCluster
      name: "target-cluster"
    path: control_plane_ip.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: OpenStackCluster
      name: "target-cluster"
    path: dns_servers.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: OpenStackCluster
      name: "target-cluster"
    path: external_network_id.json

patchesStrategicMerge:
  - cluster_clouds_yaml_patch.yaml
  - control_plane_ip_patch.yaml
  - control_plane_config_patch.yaml
  - ssh_key_patch.yaml
  - control_plane_machine_count_patch.yaml
  - control_plane_machine_flavor_patch.yaml
