
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
- apiGroups:
  - metal3.io
  resources:
  - hardwareclassifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - hardwareclassifications/status
  verbs:
  - get
  - patch
  - update
