apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO (dukov) It's recocommended to upload BareMetalHost objects separately
  # otherwise nodes will hang in 'registering' state for quite a long time
  - nodes
  - ../../../../function/k8scontrol
  - ../catalogues

commonLabels:
  airshipit.org/stage: initinfra

transformers:
  - ../../../../function/k8scontrol/replacements
