apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: target-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: target-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: OpenStackCluster
    name: target-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: OpenStackCluster
metadata:
  name: target-cluster
  namespace: default
spec:
  apiServerLoadBalancerFloatingIP: ${OPENSTACK_CONTROLPLANE_IP}
  apiServerLoadBalancerPort: 6443
  cloudName: devstack
  cloudsSecret:
    name: target-cluster-cloud-config
    namespace: default
  disablePortSecurity: false
  disableServerTags: true
  dnsNameservers:
  - "${OPENSTACK_DNS_NAMESERVERS}"
  externalNetworkId: "{OPENSTACK_EXTERNAL_NETWORK_ID}"
  managedAPIServerLoadBalancer: true
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
  useOctavia: true
---
apiVersion: v1
kind: Secret
metadata:
  name: target-cluster-cloud-config
  namespace: default
data:
  cacert: ${CLOUD_CERT_B64}
  clouds.yaml: ${CLOUDS_YAML_B64}
