namePrefix: capo-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-openstack"

bases:
- crd
- webhook # Disable this if you're not using the webhook functionality.
- default

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: openstackclusters.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: openstackmachines.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: openstackmachinetemplates.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
