apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/workers-capd

patchesJson6902:
  - target:
      group: cluster.x-k8s.io
      version: v1alpha3
      kind: MachineDeployment
      name: "target-cluster-md-0"
    path: machine_count.json
