apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capg

patchesJson6902:

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: GCPCluster
      name: "target-cluster"
    path: project_name.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: GCPCluster
      name: "target-cluster"
    path: region_name.json

  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: GCPCluster
      name: "target-cluster"
    path: network_name.json

  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "target-cluster-control-plane"
    path: machine_count.json


  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: GCPMachineTemplate
      name: "target-cluster-control-plane"
    path: machine_type.json

