namePrefix: capg-

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-gcp"

bases:
- crd
- webhook # Disable this if you're not using the webhook functionality.
- default
# needs to be disabled since env variables aren't imported properly
#- data

# Enable this when conversion webhooks are implemented
#patchesJson6902:
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: gcpclusters.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: gcpmachines.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
#- target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: gcpmachinetemplates.infrastructure.cluster.x-k8s.io
#  path: patch_crd_webhook_namespace.yaml
