resources:
  - ../../../phases
patchesStrategicMerge:
  - plan.yaml
patchesJson6902:
  - target:
      group: airshipit.org
      version: v1alpha1
      kind: Clusterctl
      name: "clusterctl_init"
    path: infrastructure-providers.json
