apiVersion: airshipit.org/v1alpha1
kind: KubevalOptions
metadata:
  name: kubeval-options
  labels:
    airshipit.org/deploy-k8s: "false"
siteConfig:
  strict: true
  kubernetesVersion: "1.16.0"
  ignoreMissingSchemas: false
planName: AIRSHIPCTL_CURRENT_PLAN
planConfigs:
  phasePlan:
    kindsToSkip:
      - Clusterctl
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/versions-catalogue.yaml
      - function/airshipctl-schemas/network-catalogue.yaml
phaseName: AIRSHIPCTL_CURRENT_PHASE
phaseConfigs:
  initinfra-ephemeral:
    kindsToSkip:
      - Clusterctl
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/versions-catalogue.yaml
      - function/airshipctl-schemas/network-catalogue.yaml
  clusterctl-init-ephemeral:
    crdList:
      - function/cert-manager/v1.1.0/upstream/cert-manager.yaml
  controlplane-ephemeral:
    kindsToSkip:
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/network-catalogue.yaml
      - function/airshipctl-schemas/versions-catalogue.yaml
      - function/capi/v0.3.7/crd/bases/cluster.x-k8s.io_clusters.yaml
      - function/cacpk/v0.3.7/crd/bases/controlplane.cluster.x-k8s.io_kubeadmcontrolplanes.yaml
      - function/capm3/v0.4.0/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
      - function/capm3/v0.4.0/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
      - global/crd/baremetal-operator/metal3.io_baremetalhosts_crd.yaml
  clusterctl-init-target:
    crdList:
      - function/cert-manager/v1.1.0/upstream/cert-manager.yaml
  initinfra-target:
    kindsToSkip:
      - Clusterctl
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/network-catalogue.yaml
      - function/airshipctl-schemas/versions-catalogue.yaml
  workers-target:
    crdList:
      - global/crd/baremetal-operator/metal3.io_baremetalhosts_crd.yaml
  workers-classification:
    kindsToSkip:
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/network-catalogue.yaml
      - function/airshipctl-schemas/versions-catalogue.yaml
      - function/cabpk/v0.3.7/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigtemplates.yaml
      - function/capi/v0.3.7/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
      - function/capm3/v0.4.0/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
      - function/hwcc/crd/bases/metal3.io_hardwareclassifications.yaml
  workload-target:
    kindsToSkip:
      - VariableCatalogue
    crdList:
      - function/airshipctl-schemas/network-catalogue.yaml
      - function/airshipctl-schemas/versions-catalogue.yaml
      - function/flux/helm-controller/upstream/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
      - function/flux/source-controller/upstream/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
