apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: generated-secrets-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:v2
replacements:
- source:
    objref:
      name: generated-secrets
    fieldref: "{.isoImage.passwords.root}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_ISO_PASSWORD_ROOT%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.isoImage.passwords.deployer}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_ISO_PASSWORD_DEPLOYER%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.ephemeralClusterCa.key}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_CA_KEY%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.ephemeralClusterCa.crt}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_CA_CERT%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.ephemeralKubeconfig.certificate-authority-data}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_KUBECONFIG_CA_CERT%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.ephemeralKubeconfig.client-key-data}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_KUBECONFIG_ADMIN_KEY%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.ephemeralKubeconfig.client-certificate-data}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_KUBECONFIG_ADMIN_CERT%"]
