apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/hostgenerator-m3
  - ../../target/catalogues
  - host-generation.yaml

transformers:
  - ../../../../function/hostgenerator-m3/replacements
  - ../../../../function/airshipctl-cleanup/
