apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# When updating the release, update also the image tag in image_patch.yaml
resources:
- ipam-components.yaml

patchesStrategicMerge:
    - image_patch.yaml
    - pull_policy_patch.yaml
