apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: clusterctl_init
init-options:
  core-provider: "cluster-api:v0.3.7"
  bootstrap-providers:
    - "kubeadm:v0.3.7"
  infrastructure-providers:
    - "metal3:v0.4.0"
  control-plane-providers:
    - "kubeadm:v0.3.7"
providers:
  - name: "metal3"
    type: "InfrastructureProvider"
    variable-substitution: true
    versions:
      v0.4.0: airshipctl/manifests/function/capm3/v0.4.0
  - name: "kubeadm"
    type: "BootstrapProvider"
    variable-substitution: true
    versions:
      v0.3.7: airshipctl/manifests/function/cabpk/v0.3.7
  - name: "cluster-api"
    type: "CoreProvider"
    variable-substitution: true
    versions:
      v0.3.7: airshipctl/manifests/function/capi/v0.3.7
  - name: "kubeadm"
    type: "ControlPlaneProvider"
    variable-substitution: true
    versions:
      v0.3.7: airshipctl/manifests/function/cacpk/v0.3.7

# The default image repository and tag for a specific component
# can be overriden here
images:
  cert-manager:
    repository: "quay.io/jetstack"
  cluster-api/cluster-api-controller:
    repository: "us.gcr.io/k8s-artifacts-prod/cluster-api"
    tag: "v0.3.7"
  cluster-api/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  bootstrap-kubeadm/kubeadm-bootstrap-controller:
    repository: "us.gcr.io/k8s-artifacts-prod/cluster-api"
    tag: "v0.3.7"
  bootstrap-kubeadm/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  control-plane-kubeadm/kubeadm-control-plane-controller:
    repository: "us.gcr.io/k8s-artifacts-prod/cluster-api"
    tag: "v0.3.7"
  control-plane-kubeadm/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  infrastructure-metal3/cluster-api-provider-metal3:
    repository: "quay.io/metal3-io"
    tag: "v0.4.0"
  infrastructure-metal3/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.0"
  infrastructure-metal3/ip-address-manager:
    repository: "quay.io/metal3-io"
    tag: "v0.4.0"
  infrastructure-docker/capd-manager:
    repository: "gcr.io/k8s-staging-cluster-api"
    tag: "v20201019-v0.3.10-86-gc1647481f"
  infrastructure-docker/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.0"
  infrastructure-azure/cluster-api-azure-controller:
    repository: "gcr.io/k8s-staging-cluster-api-azure"
    tag: "v0.4.9"
  infrastructure-azure/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  infrastructure-gcp/cluster-api-gcp-controller:
    repository: "gcr.io/k8s-staging-cluster-api-gcp"
    tag: "master"
  infrastructure-gcp/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  infrastructure-openstack/capi-openstack-controller-amd64:
    repository: "gcr.io/k8s-staging-capi-openstack"
    tag: "v20200707-v0.3.1"
  infrastructure-openstack/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"


# These default images can be overridden via the `replacements/` entrypoint
additional-vars: {}
