# These rules inject networking info into the baremetal-operator  function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: baremetal-operator-networking-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:v2
replacements:
# Replace the pod & service networks
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.provisioningInterface
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.PROVISIONING_INTERFACE"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.provisioningIp
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.PROVISIONING_IP"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.dhcpRange
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.DHCP_RANGE"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.ironicAutomatedClean
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.IRONIC_AUTOMATED_CLEAN"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.httpPort
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.HTTP_PORT"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.ironicFastTrack
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.IRONIC_FAST_TRACK"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.deployKernelUrl
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.DEPLOY_KERNEL_URL"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.deployRamdiskUrl
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.DEPLOY_RAMDISK_URL"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.ironicEndpoint
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.IRONIC_ENDPOINT"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ironic.ironicInspectorEndpoint
  target:
    objref:
      kind: ConfigMap
      name: ironic-vars
    fieldrefs: ["data.IRONIC_INSPECTOR_ENDPOINT"]
