apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capz/v0.4.9

patchesJson6902:
  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha3
      kind: KubeadmControlPlane
      name: "target-cluster-control-plane"
    path: machine_count.json
  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: AzureCluster
      name: "target-cluster"
    path: cluster.json
  - target:
      group: infrastructure.cluster.x-k8s.io
      version: v1alpha3
      kind: AzureMachineTemplate
      name: "target-cluster-control-plane"
    path: machine_template.json
